"use client"

import * as React from "react"
import { useOrganization } from "@clerk/nextjs"
import { FileText, Download, Calendar, Target, Users, CheckCircle } from "lucide-react"

const SDG_LABELS: Record<string, string> = {
  "1": "No Poverty",
  "2": "Zero Hunger",
  "3": "Good Health",
  "4": "Quality Education",
  "5": "Gender Equality",
  "6": "Clean Water",
  "7": "Clean Energy",
  "8": "Decent Work",
  "9": "Industry & Innovation",
  "10": "Reduced Inequalities",
  "11": "Sustainable Cities",
  "12": "Responsible Consumption",
  "13": "Climate Action",
  "14": "Life Below Water",
  "15": "Life on Land",
  "16": "Peace & Justice",
  "17": "Partnerships",
}

async function getFundData(orgId: string) {
  const res = await fetch(`/api/funds?orgId=${orgId}`)
  if (!res.ok) return null
  return res.json()
}

async function generateReport(orgId: string, quarter: string, year: number) {
  const res = await fetch(`/api/funds/report?orgId=${orgId}&quarter=${quarter}&year=${year}`, {
    method: "POST",
  })
  if (!res.ok) return null
  return res.json()
}

const QUARTERS = [
  { value: "Q1", label: "Q1 (Jan-Mar)", months: [1, 2, 3] },
  { value: "Q2", label: "Q2 (Apr-Jun)", months: [4, 5, 6] },
  { value: "Q3", label: "Q3 (Jul-Sep)", months: [7, 8, 9] },
  { value: "Q4", label: "Q4 (Oct-Dec)", months: [10, 11, 12] },
]

export default function ReportsPage() {
  const { organization } = useOrganization()
  const [summary, setSummary] = React.useState<any>(null)
  const [quarter, setQuarter] = React.useState("Q1")
  const [year, setYear] = React.useState(2026)
  const [generating, setGenerating] = React.useState(false)
  const [report, setReport] = React.useState<any>(null)

  React.useEffect(() => {
    if (!organization?.id) return
    getFundData(organization.id).then(setSummary)
  }, [organization?.id])

  const handleGenerate = async () => {
    if (!organization?.id) return
    setGenerating(true)
    try {
      const data = await generateReport(organization.id, quarter, year)
      setReport(data)
    } catch (e) {
      console.error(e)
    }
    setGenerating(false)
  }

  const downloadPDF = () => {
    if (!report) return
    const text = `
================================================================================
${organization?.name} - ${quarter} ${year} Impact Report
================================================================================

EXECUTIVE SUMMARY
-----------------
Total Portfolio Hours: ${report.totalHours}
Companies in Portfolio: ${report.companies}
SDG Goals Addressed: ${report.sdgGoals}

SDG BREAKDOWN
-------------
${Object.entries(report.sdgBreakdown).map(([sdg, hours]) => `SDG ${sdg}: ${SDG_LABELS[sdg] || "Unknown"} - ${hours} hours`).join("\n")}

COMPANY IMPACT
------------
${report.companyImpact.map((c: any) => `${c.name}: ${c.hours} hours, SDG aligned: ${c.sdg}%`).join("\n")}

METHODOLOGY
----------
Activities tracked via portfolio company time tracking. SDG categories mapped 
according to UN Sustainable Development Goals framework. Impact verified through 
quarterly company reporting.

================================================================================
Generated by Greta Impact OS
================================================================================
`
    const blob = new Blob([text], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${organization?.name.replace(/\s+/g, "_")}_${quarter}_${year}_Impact_Report.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (!organization) {
    return (
      <div className="p-6">
        <div className="text-center py-12">
          <FileText className="w-12 h-12 mx-auto text-slate-300 mb-4" />
          <h2 className="text-lg font-semibold text-slate-700">No organization selected</h2>
        </div>
      </div>
    )
  }

  const totalHours = summary?.totalHours || 0
  const companies = summary?.companies || []
  const sdgBreakdown = summary?.sdgBreakdown || {}

  return (
    <div className="p-4 lg:p-6 space-y-6">
      <header>
        <h1 className="text-2xl font-semibold text-slate-800">LP Reports</h1>
        <p className="text-slate-500 text-sm">Generate CSRD-ready impact reports</p>
      </header>

      <div className="grid lg:grid-cols-2 gap-6">
        <div className="bg-white rounded-xl border border-slate-200 p-5">
          <h3 className="font-semibold text-slate-800 mb-4">Generate Report</h3>
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Quarter</label>
              <select value={quarter} onChange={e => setQuarter(e.target.value)} className="w-full px-3 py-2 border border-slate-300 rounded-lg">
                {QUARTERS.map(q => (
                  <option key={q.value} value={q.value}>{q.label}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Year</label>
              <select value={year} onChange={e => setYear(parseInt(e.target.value))} className="w-full px-3 py-2 border border-slate-300 rounded-lg">
                {[2025, 2026, 2027].map(y => (
                  <option key={y} value={y}>{y}</option>
                ))}
              </select>
            </div>
          </div>
          <button onClick={handleGenerate} disabled={generating} className="w-full bg-green-600 text-white py-3 rounded-lg font-medium hover:bg-green-700 disabled:opacity-50">
            {generating ? "Generating..." : "Generate Report"}
          </button>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-5">
          <h3 className="font-semibold text-slate-800 mb-4">Portfolio Summary</h3>
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-slate-600">Total Hours</span>
              <span className="font-medium text-slate-800">{totalHours}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-slate-600">Companies</span>
              <span className="font-medium text-slate-800">{companies.length}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-slate-600">Active SDGs</span>
              <span className="font-medium text-slate-800">{Object.keys(sdgBreakdown).length}</span>
            </div>
          </div>
        </div>
      </div>

      {report && (
        <div className="bg-white rounded-xl border border-slate-200 p-5 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-slate-800">{quarter} {year} Impact Report</h3>
            <button onClick={downloadPDF} className="flex items-center gap-2 text-green-600 font-medium">
              <Download className="w-4 h-4" />
              Export
            </button>
          </div>

          <div className="grid lg:grid-cols-3 gap-4">
            <div className="bg-slate-50 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <Calendar className="w-4 h-4 text-slate-400" />
                <span className="text-sm text-slate-500">Period</span>
              </div>
              <p className="font-semibold text-slate-800">{quarter} {year}</p>
            </div>
            <div className="bg-slate-50 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <Users className="w-4 h-4 text-slate-400" />
                <span className="text-sm text-slate-500">Hours</span>
              </div>
              <p className="font-semibold text-slate-800">{report.totalHours}</p>
            </div>
            <div className="bg-slate-50 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <Target className="w-4 h-4 text-slate-400" />
                <span className="text-sm text-slate-500">SDGs</span>
              </div>
              <p className="font-semibold text-slate-800">{report.sdgGoals}</p>
            </div>
          </div>

          <div>
            <h4 className="font-medium text-slate-700 mb-2">SDG Impact</h4>
            <div className="space-y-1">
              {Object.entries(report.sdgBreakdown).sort((a, b) => (b[1] as number) - (a[1] as number)).map(([sdg, hours]) => (
                <div key={sdg} className="flex items-center justify-between text-sm">
                  <span className="text-slate-600">SDG {sdg}: {SDG_LABELS[sdg] || "Unknown"}</span>
                  <span className="font-medium text-slate-800">{hours}h</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}